format = """
[](#2c6552)\
$os\
$username\
[](bg:#2a8082 fg:#2c6552)\
$directory\
[](fg:#2a8082 bg:#339f8d)\
$git_branch\
$git_status\
[](fg:#339f8d bg:#61c9c9)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#61c9c9 bg:#9ee9c4)\
$docker_context\
[](fg:#9ee9c4 bg:#abf8e4)\
$time\
[ ](fg:#abf8e4)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#2c6552"
style_root = "bg:#2c6552"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#2c6552"
disabled = true # Disabled by default

[directory]
style = "bg:#2a8082"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#61c9c9"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#9ee9c4"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#61c9c9"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#61c9c9"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#339f8d"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#339f8d"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#61c9c9"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#61c9c9"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#61c9c9"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#61c9c9"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#61c9c9"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#61c9c9"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#61c9c9"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#61c9c9"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#61c9c9"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#abf8e4"
format = '[  $time ]($style)'
