# ~/.config/starship.toml

# Inserts a blank line between shell prompts
add_newline = true

# Change command timeout from 500 to 1000 ms
command_timeout = 1000

# Change the default prompt format
format = """\
[╭╴](238)$username$hostname$directory$git_branch$git_status$battery\
$all[╰─](238)$character"""
# 
# Change the default prompt characters
[character]
success_symbol = "[](238)"
error_symbol = "[](238)"

# Shows an icon that should be included by zshrc script based on the distribution or os
# [env_var.STARSHIP_DISTRO]
# format = '[$env_value](bold yellow)'
# variable = "STARSHIP_DISTRO"
# disabled = false

# Shows the username
[username]
style_user = "white"
style_root = "white"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "on [$hostname](bold yellow) "
disabled = false

[directory]
truncation_length = 3
truncation_symbol = "…/"
home_symbol = " ~"
read_only_style = "197"
read_only = "  "
format = "at [$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
truncation_length = 12
truncation_symbol = "…/"
style = "purple"

[git_status]
format = '[\($all_status$ahead_behind\)]($style) '
style = "purple"
conflicted = "🏳"
up_to_date = " "
untracked = " "
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
stashed = " "
modified = " "
staged = '[++\($count\)](green)'
renamed = "襁 "
deleted = " "

[battery]
full_symbol = "🔋"
charging_symbol = "🔌 "
discharging_symbol = "⚡️"

[[battery.display]]  # "bold red" style when capacity is between 0% and 10%
threshold = 10
style = "bold red"

[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
threshold = 30
style = "bold yellow"

[[battery.display]]
threshold = 100
style = "bold green"


[package]
disabled = true

[c]
disabled = true

[docker_context]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[golang]
disabled = true

[gradle]
disabled = true

[haskell]
disabled = true

[java]
disabled = true

[lua]
disabled = true

[julia]
disabled = true

[nodejs]
disabled = true

[nim]
disabled = true

[rust]
disabled = true

[scala]
disabled = true

[meson]
disabled = true

[nix_shell]
disabled = true

[python]
disabled = true

[rlang]
disabled = true

[ruby]
disabled = true

[spack]
disabled = true
